alerts:
  console: true
  discord:
    avatar_url: https://i.imgur.com/cbcdc26e-066f-4eec-9473-bd99e331e161.jpg
    enabled: true
    everyone_threshold: 95
    mention_everyone: false
    username: Unhedged Bot
    webhook_url: https://discord.com/api/webhooks/1473940255622168650/zBdqtLMLH8xtqDdxWbkqgFgCHjEKOesK9jbjKeVmRlGs7ExP54iC_nw3p3zj4tCa8g0L
  sound: C:\Windows\Media\notify.wav
betting:
  base_amount: 10
  max_amount: 100
  min_confidence: 75
display:
  update_interval: 60
exchange: bybit
indicators:
  bollinger_bands:
    enabled: true
    period: 20
    std: 2
  ema:
    enabled: true
    long: 21
    short: 9
  macd:
    enabled: true
    fast: 12
    signal: 9
    slow: 26
  rsi:
    enabled: true
    period: 14
  volume:
    enabled: true
    period: 20
smart_timing:
  enabled: true
  hourly:
    alert_end: 45
    alert_start: 40
    scrape_minute: 1
  two_hourly:
    alert_end: 105
    alert_start: 100
    scrape_minute: 1
symbols:
- BTCUSDT
- ETHUSDT
- SOLUSDT
- CCUSDT
thresholds:
  min_confidence: 75
  rsi_overbought: 70
  rsi_oversold: 30
  volume_spike: 150
timeframe: 5m
unhedged:
  api_key: ak_rHWj55mvAzifWvuVnRZDkGcasjFwHwsshgZNpKXXVCIOHIYk
  enabled: true
  manual_markets:
    BTCUSDT: cmltcowpl032n0swjkxggw0bl
    CCUSDT: cmltcox3j032v0swjykla75na
    ETHUSDT: cmltcowwb032r0swjzeocmes9
    SOLUSDT: cmltcox9w032z0swj7uv4147p
